### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by katherinebenjamin** [mschoeffler1/ds_portfolio#5]
@masongallo @lemonsoup

Hi Michael,

Great job on your final project! I really the visuals you used in your powerpoint (especially your religiosity slide). It was good to see the data you are working with at that level. I found myself looking at the map for a while trying to figure out which areas of the country are the most religious! I look forward to seeing the final product, with your take-away and results included at the end.

I think you made a great choice using logistic regression. Do you think you would try Naive Bayes or Random Forest on this dataset in the future? Your data is very clear and you did a great job mapping things out. Your headings helped me follow along. I see that in your exploration that the “FICO score” feature is strongly predictive. In your powerpoint, could you explain to the class how a FICO scoring model works?

I’m just wondering, do you think for this project there was another way to predict if a person is religious besides their geographical location? I think you made a great choice, I’m just curious if you started out with any other ideas. Did the data you used take into account if the people living in the communities are full-time/ part-time/ renters? I don’t think it would make too much of a difference in the overall landscape of most communities (unless its a seasonal location like Nantucket that expands its population x10 in the summer), I’m just curious.

For a future project, do you think different religious beliefs play a role in paying back loans? It could be fun to compare different religious communities to each other, and see if you find a correlation in particular religions and paying back loans. 

Overall, I loved your project – very interesting insights!

**Comment by mschoeffler1** [comment]
Kate - thank you for the feedback - will be very helpful in explaining this better. 

Some specific answers: I'm hopeful random forest will be helpful in scoring more accurately. I didn't use them for determining religiousity because I thought there might be interpretation issues. 

The specific religions would certainly be interesting to look at too. 

Finally, I didn't realize until you said it, but FICO is jargon. I'll explain during the presentation. 

Thanks for the detailed feedback!
